name: Deploy to DEV on dev push

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            export PATH=/home/ubuntu/.nvm/versions/node/v20.19.2/bin:$PATH
            cd /home/ubuntu/upstage-open-chat/upstage-open-chat
            git reset --hard HEAD
            git checkout dev
            git pull origin dev
            npm install
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
            sudo systemctl restart upstage.service
